name: ML Model CI/CD

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision pytest
        
    - name: Train model
      run: |
        cd mnist_project/src
        python train.py
        
    - name: Run tests
      run: |
        cd mnist_project
        python -m pytest src/tests/
        
    - name: Upload model artifact
      uses: actions/upload-artifact@v2
      with:
        name: trained-model
        path: mnist_project/src/model_mnist_*.pth 
